default:
  image: maven:3.8.5-openjdk-17
  tags:
    - azure
    - docker
    - testing

cache:
  paths:
    - .m2/repository/
  key: maven-$CI_COMMIT_REF_SLUG

stages:
  - build
  - test

build-job:
  stage: build
  script:
    - mvn clean compile

test-job:
  stage: test
  script:
    - echo "Running TestNG tests"
    - mvn test -Dduration=500
  artifacts:
    paths:
      - test-output/
